# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16a96eaee33ff462c0439222e16376b8dcdc2be93fa2d4e876d0bcaa811b86f7397a170ba21f0c83b1c10e6be55c5274dd6c47018d9cc3c2065cdbb1a97ca0bd

test:
  secret_key_base: cf25ec00bfaa00e04e2cd5c338a078b2d6e46dd012597be957443325566ac3e31fb96722d87917d3175afb28953154b0757a6debd30578f80e8669a887c93312

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
